### ISSUE TITLE
Android HttpCertificatePinningPlugin issue

### ISSUE THREAD

**Issue by nrobi144** [diefferson/http_certificate_pinning#58]
### Stacktrace
```
plugins/GeneratedPluginRegistrant.java:114: error: cannot find symbol
      flutterEngine.getPlugins().add(new diefferson.http_certificate_pinning.HttpCertificatePinningPlugin());
                                                                            ^
  symbol:   class HttpCertificatePinningPlugin
  location: package diefferson.http_certificate_pinning
```

### Version
```
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.13.0
  
http_certificate_pinning: 2.1.1
```
